version: "3.6"

services:
  client:
    networks:
      - traefik-public
      - default
    image: "${DOCKER_IMAGE_CLIENT-ncaclient}:${TAG-latest}"
    build:
      context: .
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      restart_policy:
        window: 30s
        condition: on-failure
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${STACK_NAME}-client-https.entrypoints=https
        - traefik.http.routers.${STACK_NAME}-client-https.tls=true
        - traefik.http.routers.${STACK_NAME}-client-https.rule=(Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)) && (Path(`/latest.js`) || Path(`/latest.js.map`))
        - traefik.http.middlewares.${STACK_NAME}-client-compress.compress=true
        - traefik.http.services.${STACK_NAME}-client.loadbalancer.server.port=80
networks:
  traefik-public:
    external: true
