name: Bundle

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker/compose

    steps:
    - uses: actions/checkout@v2

    - name: Build client image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        registry: ghcr.io
        username: nocookie-analytics
        password: "${{ secrets.GITHUB_TOKEN }}"
        image_name: nca-client
        image_tag: ${{ github.sha }}
        push_git_tag: true
