name: Bundle

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker/compose

    env:
      DOCKER_IMAGE_CLIENT: eu.gcr.io/no-cookie-analytics/nca-client

    steps:
    - name: Install python
      run: |
        apk add --no-cache python3

    - name: Setup env file
      run: |
        echo "TAG=$GITHUB_SHA" | sed 's|/|-|g' >> .env

    - uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Docker login
      run: |
        gcloud auth configure-docker

    - name: Build docker images
      run: |
        export BRANCH_TAG=$(echo "$GITHUB_REF" | sed 's|/|-|g')
        docker build . --progress=plain -t $DOCKER_IMAGE_CLIENT:$GITHUB_SHA

    - name: Push docker
      run: |
        docker image ls
        export BRANCH_TAG=$(echo "$GITHUB_REF" | sed 's|/|-|g')
        docker tag $DOCKER_IMAGE_CLIENT:$GITHUB_SHA $DOCKER_IMAGE_CLIENT:$BRANCH_TAG

        docker push $DOCKER_IMAGE_CLIENT:$BRANCH_TAG

        docker push $DOCKER_IMAGE_CLIENT:$GITHUB_SHA
