name: Bundle

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    container: docker/compose

    env:
      DOCKER_REGISTRY: eu.gcr.io
      DOCKER_IMAGE_NAME: nca-client

    steps:
    - uses: actions/checkout@v2

    - name: Build client image
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: _json_key
        password: "${{ secrets.GCP_SA_KEY }}"
        registry: ${{ env.DOCKER_REGISTRY }}
        image_name: ${{ env.DOCKER_IMAGE_NAME }}
        image_tag: latest
        push_git_tag: true
        context: .
